### ISSUE TITLE
Use existing RG when the module creates NSG and RT

### ISSUE THREAD

**Issue by BHellstream** [haflidif/terraform-azurerm-alz-subnet#2]
Nice collection of workarounds. 

i have a use case where i would like to use an existing resource group instead of creating a new one for each subnet. 
so basically add an option to send existing RG name to use when creating the nsg and rt. 

Really appreciate the module and why section, made it really easy describing the issues to colleagues.

**Comment by haflidif** [comment]
Hey @BHellstream thank you very much for your feedback.

I'm currently working on Version 2.0 that will introduce exactly this functionality that you are asking for 💯 I plan to be finished with the new version of the module within few days.

I'm really thankful for your feedback and glad that it had helped you.

**Comment by qaiserali** [comment]
Hi,

We are also waiting for this function. I would appreciate it if you could solve it at the earliest. 

Thank you!

**Comment by qaiserali** [comment]
@haflidif Any progress on this?

**Comment by haflidif** [comment]
> @haflidif Any progress on this?

Hey thanks for your messages, im currently working on it, has been bit swamped with my work lately and as this is done off hours, I haven't been able to prioritize it as much as I would have, but there is a solution around the corner.

Thank you for your patience

**Comment by haflidif** [comment]
@qaiserali and @BHellstream I finally got some time to work on the issue and now the functionality has been released in [v2.0.0](https://github.com/haflidif/terraform-azurerm-alz-subnet/releases/tag/2.0.0) 

Thank you very much for raising the issue, and hopefully it will resolve the requirements you have, cheers!
